# Generated by Django 2.0.7 on 2018-08-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='last_update_time',
            new_name='last_updated_time',
        ),
    ]
