# Generated by Django 2.0.7 on 2018-08-09 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_readnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readnum',
            old_name='readNum',
            new_name='read_num',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='read_num',
        ),
    ]
